version: "2.1"
services:
  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: kltn_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    networks:
      - kltn
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  tika:
    image: apache/tika:1.28.4-full
    container_name: kltn_apache_tika
    command: -c /tika-config.xml
    restart: on-failure
    ports:
      - "9998:9998"
    volumes:
      - ./tika-config.xml:/tika-config.xml
    networks:
      - kltn

  redis:
    image: redis:latest
    container_name: kltn_redis
    ports:
      - "6379:6379"
    networks:
      - kltn

  mysql-db:
    image: mysql:8.0.33
    container_name: kltn_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bach1912
      MYSQL_DATABASE: kltn
    depends_on:
      - redis
      - elasticsearch
      - tika
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kltn

  fastapi:
    build:
      dockerfile: Dockerfile
      context: "./python"
    container_name: kltn_fastApi
    ports:
      - "8000:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
    command: sh -c "chmod +x ./init.sh && ./init.sh"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./python:/var/www/html/kltn/python
    networks:
      - kltn

  express:
    build:
      dockerfile: Dockerfile
      context: "./be"
    container_name: kltn_express
    ports:
      - "5000:5000"
    depends_on:
      - fastapi
    volumes:
      - mysql_data:/var/lib/mysql
      - ./be:/var/www/html/kltn/be
    networks:
      - kltn

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    depends_on:
      - elasticsearch
    networks:
      - kltn
  react-frontend:
    build:
      dockerfile: Dockerfile
      context: "./fe"
    container_name: kltn_react
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/var/www/html/kltn/fe
    depends_on:
      - fastapi
      - express
    networks:
      - kltn

volumes:
  mysql_data:

networks:
  kltn:
